# Generated by Django 5.2.5 on 2025-08-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=50)),
                ('cat_foto', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('cul_nombre', models.CharField(max_length=50)),
                ('cul_apellido', models.CharField(max_length=50)),
                ('cul_correo', models.CharField(max_length=50)),
                ('cul_telefono', models.CharField(max_length=15)),
                ('cul_direccion', models.CharField(max_length=100)),
                ('cul_region', models.CharField(max_length=50)),
                ('cul_postal', models.CharField(max_length=10)),
                ('cul_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=50)),
                ('emp_apellido', models.CharField(max_length=50)),
                ('emp_correo', models.CharField(max_length=50)),
                ('emp_telefono', models.CharField(max_length=15)),
                ('emp_direccion', models.CharField(max_length=100)),
                ('emp_fecha_contrato', models.DateField()),
                ('emp_fecha_nacimiento', models.DateField()),
                ('emp_foto', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('prv_nombre', models.CharField(max_length=50)),
                ('prv_contacto', models.CharField(max_length=50)),
                ('prv_correo', models.CharField(max_length=50)),
                ('prv_telefono', models.CharField(max_length=15)),
                ('prv_direccion', models.CharField(max_length=100)),
                ('prv_region', models.CharField(max_length=50)),
                ('prv_postal', models.CharField(max_length=10)),
                ('prv_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('ord_fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=50)),
                ('pro_precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pro_stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg_cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
